#!/usr/bin/env python
# coding: utf-8

# In[5]:


#ble ikke ferdig med koden, etter flere feil fikk jeg det ikke til å funke. 
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp
import numpy as np    


# In[8]:


def demand(c,Q,y,pb):
    demand = (c.log(Q) - (-4.507 + 0.841 * y + 0.2775 * pb)) / (-0.397)
    return demand
    


# In[11]:


def supply(c,Q,N,X,pf,t):
    supply_short_run  = ((1 - 0.631) * c.log(NQ+X) - (2.030 - 0.146 * pf + 0.0184 * t))/(0.221)
    return supply

def plot_year(df,year): 
    pass


# In[14]:


def supply_curve_short_run(c,Q,N,X,pf,t,Q_fitted):
    supply_curve_short_run  = (((c.log(NQ+X)-(2.030-0.146 * pf+0.0184 * t+0.631 * c.log(NQ_fitted+X)))) / 0.221)
    return supply_curve_short_run


# In[15]:



    d=df[df['YEAR']==year].to_dict(orient='records')[0]
    
    cpi=d['CPI']
    y=np.log(d['Y'])
    pb=np.log(d['PBEEF']/cpi)
    N=d['POP']
    X=d['QPRODA']/1439-d['Q']*d['POP']
    pf=np.log(d['PF']/cpi)
    t=d['TIME']


# In[ ]:



    Q_fitted=equate_q(y,pb,N,X,pf,t) 
    
    
    plt.show()

